# Generated by Django 4.2.5 on 2023-10-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
