# Generated by Django 4.2.5 on 2023-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.AddField(
            model_name='room',
            name='ai_Tag',
            field=models.ManyToManyField(related_name='rooms', to='chat.ai_tag', verbose_name='ai_Tag'),
        ),
    ]
