# Generated by Django 4.2.5 on 2023-10-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_room_gender_room_chatgpt_room_claude2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ai_Tag',
        ),
    ]
